sudo: required
services:
  - docker

before_install:
  - docker build -t imran/docker-react -f Dockerfile.dev .

script:
  - docker run imran/docker-react npm run test -- --coverage

# deploy:
#   provider: heroku
#   api_key:
#     secure: "YOUR ENCRYPTED API KEY"
#   on:
#     branch: master



# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "app-name"
#   env: "app-env"
#   bucket_name: "s3-bucket-name"
#   bucket_path: "app-name"
#   on:
#       branch: master
#   access_key_id: $....
#   secret_access_key: 
#         secure: $....