sudo: required
services:
  - docker

before_install:
  - docker build -t imran/docker-react -f Dockerfile.dev .

script:
  - docker run imran/docker-react npm run test -- --coverage

# deploy:
#   provider: heroku
#   api_key:
#     secure: "YOUR ENCRYPTED API KEY"